name: tiktok_clone
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: any
  cupertino_icons: ^1.0.6
  font_awesome_flutter: 10.3.0
  video_player: 2.4.10
  visibility_detector: 0.3.3
  google_fonts: 4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  generate: true

  uses-material-design: true

  assets:
    - assets/videos/
    - assets/images/
flutter_intl:
  enabled: true
